nodes=8
search_time= 5
[min_avsp,min_servers] = BestRandAvSP(search_time,nodes)
search_time= 30
[min_avsp,min_servers] = BestRandAvSP(search_time,nodes)
nodes=10
search_time= 5
[min_avsp,min_servers] = BestRandAvSP(search_time,nodes)
search_time= 30
[min_avsp,min_servers] = BestRandAvSP(search_time,nodes)