current_best_n= [5    36    19    11    62    83    51    21    67    66]
search_time= 5
[min_ConNP,min_servers] = BestHCConNP(search_time,current_best_n)
search_time= 30
[min_ConNP,min_servers] = BestHCConNP(search_time,current_best_n)
current_best_n= [ 15    28    27    20    83    64    59    65] 
search_time= 5
[min_ConNP,min_servers] = BestHCConNP(search_time,current_best_n)
search_time= 30
[min_ConNP,min_servers] = BestHCConNP(search_time,current_best_n)